// General app actions
export const DBNAME = 'FilterBubblerDB'
export const UPDATE_APP_VERSION = 'UPDATE_APP_VERSION'
export const APP_VERSION = '0.0.1'

export const CHANGE_CLASSIFICATION = 'CHANGE_CLASSIFICATION'
export const ANALYZE_CONTENT = 'ANALYZE_CONTENT'
export const ACTIVE_URL = 'ACTIVE_URL'
export const UI_REQUEST_ACTIVE_URL = 'UI_REQUEST_ACTIVE_URL'
export const REQUEST_ACTIVE_TAB_TEXT = 'REQUEST_ACTIVE_TAB_TEXT'
export const REPORT_ERROR = 'REPORT_ERROR'
export const SET_CONTENT = 'SET_CONTENT'
export const MAIN_TAB = 'MAIN_TAB'

// Servers
export const ADD_SERVER = 'ADD_SERVER'
export const UI_ADD_SERVER = 'UI_ADD_SERVER'

// Recipes
export const ADD_RECIPE = 'ADD_RECIPE'
export const UI_ADD_RECIPE = 'UI_ADD_RECIPE'
export const REMOVE_RECIPE = 'REMOVE_RECIPE'
export const UI_REMOVE_RECIPE = 'UI_REMOVE_RECIPE'
export const LOAD_RECIPE = 'LOAD_RECIPE'
export const UPDATE_RECIPES = 'UPDATE_RECIPES'
export const ADD_CORPUS_CLASSIFICATION = 'ADD_CORPUS_CLASSIFICATION'
export const UI_SHOW_ADD_RECIPE = 'UI_SHOW_ADD_RECIPE'
export const APPLY_RESTORED_STATE = 'APPLY_RESTORED_STATE'
export const UI_LOAD_RECIPE = 'UI_LOAD_RECIPE'
export const UPDATE_RECIPE = 'UPDATE_RECIPE'
export const UI_UPDATE_RECIPE = 'UI_UPDATE_RECIPE'

// Corpora and classifications
export const ADD_CORPUS = 'ADD_CORPUS'
export const UI_ADD_CORPUS = 'UI_ADD_CORPUS'
export const REMOVE_CORPUS = 'REMOVE_CORPUS'
export const UI_REMOVE_CORPUS = 'UI_REMOVE_CORPUS'
export const ADD_CLASSIFICATION = 'ADD_CLASSIFICATION'
export const UI_ADD_CLASSIFICATION = 'UI_ADD_CLASSIFICATION'
export const ADD_CLASSIFICATION_URL = 'ADD_CLASSIFICATION_URL'
export const UI_ADD_CLASSIFICATION_URL = 'UI_ADD_CLASSIFICATION_URL'
export const REMOVE_CLASSIFICATION_URL = 'REMOVE_CLASSIFICATION_URL'
export const UI_REMOVE_CLASSIFICATION_URL = 'UI_REMOVE_CLASSIFICATION_URL'
export const APPLY_CORPUS = 'APPLY_CORPUS'
export const APPLY_CORPORA = 'APPLY_CORPORA'

// UI Text
export const COULD_NOT_FETCH_TAB_TEXT = 'Could not fetch text from the active tab'
